---
echo: false
warning: false
---

```{r}
library(surveydown)
```

::: {#page1 .sd-page}

# Household Survey
Fill the form as honestly as possible.

###### A.  SOCIO-DEMOGRAPHIC CHARACTERISTICS OF RESPONDENTS

```{r}

# 1
sd_question(
  type  = 'text',
  id    = 'resp_name',
  label = "Record the name of the respondent",
)

# 2
sd_question(
  type  = 'mc',
  id    = 'resp_sex',
  label = "Record sex of the respondent",
  option = c(
    'Male' = 1,
    'Female' = 2,
    'Other' = 3
  )
)

# 3
sd_question(
  type  = 'text',
  id    = 'resp_sex_other',
  label = "Specify other sex",
)

# 4
sd_question(
  type  = 'mc_buttons',
  id    = 'resp_age',
  label = "How old are you?",
  option = c(
    "Below 18 yrs" = 1, 
    "18-20 yrs" = 2,
    "21- 25 yrs" = 3,
    "26-30 yrs" = 4,
    "31-35 yrs" = 5,
    "36-40 yrs" = 6,
    "41-45 yrs" = 7,
    "46- 50 yrs" = 8,
    "51-60 yrs" = 9,
    "Above 61 yrs" = 10
  )
)

# 5
sd_question(
  type  = 'select',
  id    = 'resp_educ',
  label = "What is the highest level of schooling you have attained?",
  option = c(
    "None" = 1,
    "Some primary education" = 2,
    "Completed Primary" = 3,
    "Secondary" = 4,
    "College" = 5,
    "University" = 6,
    "Other" = 7
  )
)

# 6
sd_question(
  type  = 'text',
  id    = 'resp_educ_other',
  label = "Specify other highest level of schooling you have attained."
)

# 6
sd_question(
  type  = 'mc',
  id    = 'resp_hse_type',
  label = "Indicate the household type you belong to",
  option = c(
    "Male headed" = 1,
    "Female headed" = 2,
    "Child headed" = 3
  )
)

```

```{r}
sd_next(next_page = 'page2')
```

:::

::: {#page2 .sd-page}

###### B. ENERGY ACCESS- ELECTRICITY

```{r}

# 7
sd_question(
  type  = 'mc',
  id    = 'access_elect',
  label = "Do you have access to electricity? ",
  option = c(
    "Yes" = 1,
    "No" = 2
  )
)

# 8
sd_question(
  type  = "numeric",
  id    = "cost_elect",
  label = "How much of your household income do you spend on electricity?"
)

sd_next(next_page = 'end')
```

:::

::: {#end .sd-page}

## End

Thank you for your time!

```{r}
sd_close("Exit Survey")
```

:::
